name: FlyingBow-OG
version: '1.2'
main: me.barny1094875.flyingbowog.FlyingBow_OG
author: barny1094875
api-version: 1.18
commands:
  givebow:
    usage: /givebow
permissions:
  flyingbow.cangive:
    default: op