name: FlyingBow-OG
version: '1.4'
main: me.barny1094875.flyingbowog.FlyingBow_OG
author: barny1094875
api-version: 1.18
depend: [NBTAPI]
commands:
  flyingbow:
    usage: /flyingbow
permissions:
  flyingbow.cangive:
    default: op